#!/bin/bash
PWD=`pwd`
PROJ=`realpath ..` 
PATH=${PROJ}/node_modules/.bin:$PATH

EXAMPLE=${PROJ}/example
EXAMPLE_DIST=${PROJ}/example/dist

# these are the examples 
BEZ=${EXAMPLE}/bez
SQUARE=${EXAMPLE}/square
MOTION=${EXAMPLE}/motion
TABLE=${EXAMPLE}/table
WHEEL=${EXAMPLE}/wheel

WEBPACK=${PROJ}/node_modules/.bin/webpack
INDEXJS=${PROJ}/src/index.js
BUNDLE=${PROJ}/dist/accelerate.js
BUNDLE_MIN=${PROJ}/dist/accelerate.min.js

function public:lint {
    public:clean ${1}
    esw $1 -c ../.eslintrc.json
    # esw $1 --fix -c ../.eslintrc.json
}

function public:build {
  webpack  --devtool source-map ${1}/main.js ${1}/${1}_bundle.js  
}

function public:watch {
  webpack -w  --devtool source-map ${1}/main.js ${1}/${1}_bundle.js 
}

function public:clean {
  rm -fv ${1}/*bundle*
}
## tasks related to example ###############################

#### bez
function public:bez_clean {
  rm -fv ${BEZ}/*bundle*
}
function public:bez_build {
  webpack  --devtool source-map ${BEZ}/bez.js ${BEZ}/bez_bundle.js
}
function public:bez_watch {
  webpack -w  --devtool source-map ${BEZ}/bez.js ${BEZ}//bez_bundle.js 
}
function public:bez_lint {
  public:lint bez
}

#### square
function public:square_clean {
  rm -fv ${SQUARE}/*bundle*
}
function public:square_build {
  webpack  --devtool source-map ${SQUARE}/square.js ${SQUARE}/square_bundle.js
}
function public:square_watch {
  webpack -w  --devtool source-map ${SQUARE}/square.js ${SQUARE}/square_bundle.js 
}
function public:square_lint {
  public:lint square
}

#### motion
function public:motion_clean {
  rm -fv ${MOTION}/*bundle*
}
function public:motion_build {
  webpack  --devtool source-map ${MOTION}/main.js ${MOTION}/motion_bundle.js
}
function public:motion_watch {
  webpack -w  --devtool source-map ${MOTION}/main.js ${MOTION}/motion_bundle.js 
}
function public:motion_lint {
  public:lint motion
}

#### wheels
function public:wheel_clean {
  rm -fv ${WHEEL}/*bundle*
}
function public:wheel_build {
  webpack  --devtool source-map ${WHEEL}/main.js ${WHEEL}/wheel_bundle.js
}
function public:wheel_watch {
  webpack -w  --devtool source-map ${WHEEL}/main.js ${WHEEL}/wheel_bundle.js 
}
function public:wheel_lint {
  public:lint wheel
}

#### table
function public:table_clean {
  rm -fv ${TABLE}/*bundle*
}
function public:table_build {
  webpack  --devtool source-map ${TABLE}/main.js ${TABLE}/table_bundle.js
}
function public:table_watch {
  webpack -w  --devtool source-map ${TABLE}/main.js ${TABLE}/table_bundle.js 
}
function public:table_lint {
  public:lint table
}


## all
function public:ex_clean {
  ./taskfile bez_clean
  ./taskfile motion_clean
  ./taskfile table_clean
  ./taskfile square_clean
}

function public:ex_lint {
  ./taskfile bez_lint
  ./taskfile motion_lint
  ./taskfile table_lint
  ./taskfile square_lint
}


function public:ex_build {
  ./taskfile bez_build
  ./taskfile motion_build
  ./taskfile table_build
  ./taskfile square_build
}
## tasks related to example ###############################



# ------------------------------------------
# DEFAULT public: list all possible commands
#
function public:help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | sed -En 's/public:(.*)/\1/p' | cat -n
}

# ---------- Do NOT edit below --------------

TIMEFORMAT="Task completed in %3lR"
SUBCMD=$1
shift 1
TIME=time
public:${SUBCMD} ${@}

# time "public:${SUBCMD} ${@}"  # make help default
